### ISSUE TITLE
No file saved in "experiments" folder on MacOS

### ISSUE THREAD

**Issue by Tong-ZHAO** [sgsellan/swept-volumes#1]
Thanks for the nice demo. I  ran the demo on MacOS with the precompiled version, but after computing the swept volume (here of a complex engine mesh) the folder "experiments/dd-mm-hh-mm" was empty. Could you help us to solve this issue? 

Don't hesitate to contact me if you need further information. Thanks very much ^^

**Comment by sgsellan** [comment]
Hi @Tong-ZHAO ! 

Thanks for enjoying my code.

Can you try if the latest commit fixes this issue?

**Comment by Tong-ZHAO** [comment]
Hi @sgsellan , thanks so much for your quick action! Yes I confirm that it works well and saves all the files in the output folder. Great job!
