### ISSUE TITLE
The loops in file 'Sparse Continuation' do not converge

### ISSUE THREAD

**Issue by youjianguo04** [sgsellan/swept-volumes#2]
Hello @sgsellan ,your algorithm has really good results.
I tried to run your code after reading your paper but it did not work.
After testing ,I think the While loop in 'Sparse_Continuation' is stuck in a dead loop,but the same file runs successfully in Gpytoolbox,I would like to ask why.

**Comment by sgsellan** [comment]
Hi! Could you please share a minimal working example of this?

**Comment by youjianguo04** [comment]
Sorry to bother you,the problem has been fixed!
