### ISSUE TITLE
Couldn't find some missing header files

### ISSUE THREAD

**Issue by XYZ-Lenari** [sgsellan/swept-volumes#3]
Hello, sorry to bother you, I want to run your project on Windows, but the error header files in the picture do not exist in the imgui folder, I looked for the various versions of libigl and did not have the imgui folder with these header files in their entirety. Probably could also go to imgui's file, but it has 96 versions, which dissuaded me. So I'm here to ask for your help, and I'm looking forward to hearing from you!
![error](https://github.com/sgsellan/swept-volumes/assets/117287149/2a322543-4f2b-4303-896b-660131e22026)

**Comment by sgsellan** [comment]
Hi!

I currently do not have access to a Windows machine to debug this, so I will keep this issue up until I manage to solve it.

Have you tried running the swept volumes [implementation](https://gpytoolbox.org/0.2.0/copyleft/swept_volume/) in gpytoolbox? If that would work, it is merely a better maintained wrapper of this C++ repo, so I would recommend you use that. Or is there a reason you need a specific C++ implementation?

**Comment by XYZ-Lenari** [comment]
I've only used gpytoolbox in MATLAB before, and I haven't actually used it yet.
I would like to use your project to generate a sweep body of the grinding wheel along a set trajectory and perform a Boolean operation with the workpiece to simulate the machining process. So I might need to add something to the project that can set the sweep trajectory? 
In addition, it may need to be integrated into the CAM system platform in the future, C++ is fine, and python can also be used. 
So, I'll try to use gpytoolbox. Thank you very much for your reply!

**Comment by sgsellan** [comment]
Great! Feel free to post an issue on gpytoolbox if you encounter any problems.
