### ISSUE TITLE
Thin body swept volume generate

### ISSUE THREAD

**Issue by AGreedBoy** [sgsellan/swept-volumes#5]
Hello, sorry to bother you. Thank you for your sewpt volume generation algorithm. Your paper is excellent, and I also used your code to generate the desired swept volume.However, when generating the swept volume of thin-walled objects, it seems that thin-walled parts can only be generated by reducing voxel size. Is there any method for processing thin-walled objects that can generate the correct swept volume without reducing voxel points? I'm looking forward to hearing from you!

**Comment by sgsellan** [comment]
Hi!

Thank you for your message. Unless I am misunderstanding you, I think what you're describing is a fundamental limitation of using a grid to compute and store the swept volume: features of size smaller than the grid resolution will simply be ignored. May I ask what your object and trajectory are, and what application you have in mind? I may be able to give a better alternative then.

**Comment by AGreedBoy** [comment]
My model is a hollow cylinder with a very small thickness, for example, a cylinder thickness of 0.3. When the voxel grid size is 3, when the cylinder moves along the axis, the swept volume will not be generated because all eight vertices of a single voxel point are considered to be outside the object. Can we handle this situation by determining whether the voxel's edge intersects the cylinder?
![Uploading Lesson54.png…]()

**Comment by sgsellan** [comment]
I see! Yeah, in that case, I think it's a pretty fundamental problem of any grid-based strategy. Have you tried any of the "explicit methods" listed in [our paper](https://www.silviasellan.com/pdf/papers/swept-volumes.pdf)? The ones in the paragraph in Sec. 2 that starts with " Since all points ... "

**Comment by AGreedBoy** [comment]
Thank you for your answer. I will carefully read these papers again. Thank you for providing these papers and ideas! It has been very helpful to me.   ^_^

**Comment by sgsellan** [comment]
Glad I could help!
